spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongo://localhost:27017/airecommendationfitness
      database: airecommendationfitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8083